-- Consulta 2: Oferta de Plazas por Empresa

SELECT
    emp.NOMBRE AS EMPRESA,
    COUNT(p.ID_PLAZA) AS CANTIDAD_PLAZAS
FROM EMPRESA emp
LEFT JOIN PLAZA p ON emp.ID_EMPRESA = p.ID_EMPRESA
GROUP BY emp.NOMBRE
ORDER BY CANTIDAD_PLAZAS DESC;