-- Consulta 4: Estudiantes en Repitencia

SELECT DISTINCT
    e.NOMBRE_COMPLETO,
    i.NOMBRE AS INSTITUTO,
    ce.NOMBRE AS CONTACTO_VALIDADOR,
    ec.NOMBRE AS ESTADO_COLOCACION
FROM ESTUDIANTE e
JOIN INSTITUTO i          ON e.ID_INSTITUTO = i.ID_INSTITUTO
JOIN COLOCACION c         ON e.CARNE = c.ID_ESTUDIANTE
JOIN ESTADO_COLOCACION ec ON c.ID_ESTADO = ec.ID_ESTADO
LEFT JOIN BITACORA b      ON c.ID_COLOCACION = b.ID_COLOCACION
LEFT JOIN CONTACTO_EMPRESARIAL ce ON b.ID_CONTACTO_VALIDADOR = ce.ID_CONTACTO
WHERE e.ES_REPITENCIA = 1;