-- SECTOR_ECONOMICO
SET DEFINE OFF

INSERT INTO SECTOR_ECONOMICO (ID_SECTOR, NOMBRE) 
VALUES (1, 'Industria');

INSERT INTO SECTOR_ECONOMICO (ID_SECTOR, NOMBRE) 
VALUES (2, 'Servicios');

INSERT INTO SECTOR_ECONOMICO (ID_SECTOR, NOMBRE) 
VALUES (3, 'Comercio');

INSERT INTO SECTOR_ECONOMICO (ID_SECTOR, NOMBRE) 
VALUES (4, 'Tecnología');

INSERT INTO SECTOR_ECONOMICO (ID_SECTOR, NOMBRE) 
VALUES (5, 'Agricultura y Agroindustria');


-- DEPARTAMENTO
SET DEFINE OFF

INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) 
VALUES (1, 'Guatemala');

INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) 
VALUES (2, 'Sacatepéquez');

INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) 
VALUES (3, 'Quetzaltenango');

INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) 
VALUES (4, 'Escuintla');


-- MUNICIPIO
SET DEFINE OFF

INSERT INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE, ID_DEPARTAMENTO) 
VALUES (1, 'Guatemala', 1);

INSERT INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE, ID_DEPARTAMENTO) 
VALUES (2, 'Villa Nueva', 1);

INSERT INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE, ID_DEPARTAMENTO) 
VALUES (3, 'Mixco', 1);

INSERT INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE, ID_DEPARTAMENTO) 
VALUES (4, 'Antigua Guatemala', 2);

INSERT INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE, ID_DEPARTAMENTO) 
VALUES (5, 'Quetzaltenango', 3);

INSERT INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE, ID_DEPARTAMENTO) 
VALUES (6, 'Escuintla', 4);

INSERT INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE, ID_DEPARTAMENTO) 
VALUES (7, 'Palín', 4);

INSERT INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE, ID_DEPARTAMENTO) 
VALUES (8, 'Santa Lucía Cotzumalguapa', 4);


-- ESTADO_COLOCACION
SET DEFINE OFF

INSERT INTO ESTADO_COLOCACION (ID_ESTADO, NOMBRE) 
VALUES (1, 'Activa');

INSERT INTO ESTADO_COLOCACION (ID_ESTADO, NOMBRE) 
VALUES (2, 'Finalizada');

INSERT INTO ESTADO_COLOCACION (ID_ESTADO, NOMBRE) 
VALUES (3, 'Cancelada');


-- TIPO_EVALUACION
SET DEFINE OFF

INSERT INTO TIPO_EVALUACION (ID_TIPO_EVALUACION, NOMBRE) 
VALUES (1, 'Parcial');

INSERT INTO TIPO_EVALUACION (ID_TIPO_EVALUACION, NOMBRE) 
VALUES (2, 'Final');


-- CRITERIO
SET DEFINE OFF

INSERT INTO CRITERIO (ID_CRITERIO, NOMBRE) 
VALUES (1, 'Puntualidad y Asistencia');

INSERT INTO CRITERIO (ID_CRITERIO, NOMBRE) 
VALUES (2, 'Calidad del Trabajo');

INSERT INTO CRITERIO (ID_CRITERIO, NOMBRE) 
VALUES (3, 'Actitud y Proactividad');

INSERT INTO CRITERIO (ID_CRITERIO, NOMBRE) 
VALUES (4, 'Dominio Técnico');

INSERT INTO CRITERIO (ID_CRITERIO, NOMBRE) 
VALUES (5, 'Trabajo en Equipo');


-- EMPRESA
SET DEFINE OFF

INSERT INTO EMPRESA (ID_EMPRESA, NOMBRE, DIRECCION, ID_SECTOR) 
VALUES (1, 'TechNova Solutions', 'Km 15 Carretera a El Salvador', 4);

INSERT INTO EMPRESA (ID_EMPRESA, NOMBRE, DIRECCION, ID_SECTOR) 
VALUES (2, 'Industrias La Aurora', 'Zona 4 de Mixco', 1);

INSERT INTO EMPRESA (ID_EMPRESA, NOMBRE, DIRECCION, ID_SECTOR) 
VALUES (3, 'Servicios Contables GT', 'Zona 10 Guatemala', 2);

INSERT INTO EMPRESA (ID_EMPRESA, NOMBRE, DIRECCION, ID_SECTOR) 
VALUES (4, 'Agropecuaria El Sol', 'Km 50 Autopista Palín-Escuintla', 5);

INSERT INTO EMPRESA (ID_EMPRESA, NOMBRE, DIRECCION, ID_SECTOR) 
VALUES (5, 'FinTech Guatemala', 'Zona 15 Edificio Avante', 4);


-- CONTACTO_EMPRESARIAL
SET DEFINE OFF

INSERT INTO CONTACTO_EMPRESARIAL (ID_CONTACTO, NOMBRE, TELEFONO, CORREO, ID_EMPRESA) 
VALUES (1, 'Ana Morales', '55551111', 'ana.morales@technova.gt', 1);

INSERT INTO CONTACTO_EMPRESARIAL (ID_CONTACTO, NOMBRE, TELEFONO, CORREO, ID_EMPRESA) 
VALUES (2, 'Carlos Fuentes', '55552222', 'cfuentes@aurora.com', 2);

INSERT INTO CONTACTO_EMPRESARIAL (ID_CONTACTO, NOMBRE, TELEFONO, CORREO, ID_EMPRESA) 
VALUES (3, 'Lucía Méndez', '55553333', 'lmendez@serviciosgt.com', 3);

INSERT INTO CONTACTO_EMPRESARIAL (ID_CONTACTO, NOMBRE, TELEFONO, CORREO, ID_EMPRESA) 
VALUES (4, 'Jorge Cifuentes', '55554444', 'jcifuentes@technova.gt', 1);

INSERT INTO CONTACTO_EMPRESARIAL (ID_CONTACTO, NOMBRE, TELEFONO, CORREO, ID_EMPRESA) 
VALUES (5, 'Sofía Valdez', '55556666', 'svaldez@agroelsol.com', 4);

INSERT INTO CONTACTO_EMPRESARIAL (ID_CONTACTO, NOMBRE, TELEFONO, CORREO, ID_EMPRESA) 
VALUES (6, 'Mario Pineda', '55557777', 'mpineda@fintech.gt', 5);

INSERT INTO CONTACTO_EMPRESARIAL (ID_CONTACTO, NOMBRE, TELEFONO, CORREO, ID_EMPRESA) 
VALUES (7, 'Diana Rosales', '55558888', 'drosales@fintech.gt', 5);


-- PLAZA
SET DEFINE OFF

INSERT INTO PLAZA (ID_PLAZA, ESPECIALIDAD_TECNICA, ID_EMPRESA, ID_CONTACTO) 
VALUES (1, 'Desarrollo de Software Web', 1, 1);

INSERT INTO PLAZA (ID_PLAZA, ESPECIALIDAD_TECNICA, ID_EMPRESA, ID_CONTACTO) 
VALUES (2, 'Soporte de Infraestructura de Redes', 1, 4);

INSERT INTO PLAZA (ID_PLAZA, ESPECIALIDAD_TECNICA, ID_EMPRESA, ID_CONTACTO) 
VALUES (3, 'Mantenimiento Eléctrico Industrial', 2, 2);

INSERT INTO PLAZA (ID_PLAZA, ESPECIALIDAD_TECNICA, ID_EMPRESA, ID_CONTACTO) 
VALUES (4, 'Asistente Contable y Auditoría', 3, 3);

INSERT INTO PLAZA (ID_PLAZA, ESPECIALIDAD_TECNICA, ID_EMPRESA, ID_CONTACTO) 
VALUES (5, 'Mantenimiento de Maquinaria Agrícola', 4, 5);

INSERT INTO PLAZA (ID_PLAZA, ESPECIALIDAD_TECNICA, ID_EMPRESA, ID_CONTACTO) 
VALUES (6, 'Analista de Datos Trainee', 5, 6);

INSERT INTO PLAZA (ID_PLAZA, ESPECIALIDAD_TECNICA, ID_EMPRESA, ID_CONTACTO) 
VALUES (7, 'Desarrollador Backend Junior', 5, 7);


-- INSTITUTO
SET DEFINE OFF

INSERT INTO INSTITUTO (ID_INSTITUTO, NOMBRE, DIRECCION, CODIGO_AUTORIZACION) 
VALUES (1, 'Instituto Técnico de Computación (ITC)', 'Zona 1 Guatemala', 'MINEDUC-001A');

INSERT INTO INSTITUTO (ID_INSTITUTO, NOMBRE, DIRECCION, CODIGO_AUTORIZACION) 
VALUES (2, 'Escuela Nacional Central Industrial (ENCI)', 'Zona 12 Guatemala', 'MINEDUC-002B');

INSERT INTO INSTITUTO (ID_INSTITUTO, NOMBRE, DIRECCION, CODIGO_AUTORIZACION) 
VALUES (3, 'Instituto Tecnológico del Sur', 'Zona 1 Escuintla', 'MINEDUC-003C');


-- CATEDRATICO
SET DEFINE OFF

INSERT INTO CATEDRATICO (ID_CATEDRATICO, IDENTIFICACION, NOMBRE, TELEFONO, ESPECIALIDAD, ID_INSTITUTO) 
VALUES (1, '2500123450101', 'Julio César Pérez', '44441111', 'Ingeniería en Sistemas', 1);

INSERT INTO CATEDRATICO (ID_CATEDRATICO, IDENTIFICACION, NOMBRE, TELEFONO, ESPECIALIDAD, ID_INSTITUTO) 
VALUES (2, '2600987650101', 'Marta Estrada', '44442222', 'Electricidad Industrial', 2);

INSERT INTO CATEDRATICO (ID_CATEDRATICO, IDENTIFICACION, NOMBRE, TELEFONO, ESPECIALIDAD, ID_INSTITUTO) 
VALUES (3, '2700555550101', 'Roberto Gómez', '44443333', 'Ciencias Económicas', 1);

INSERT INTO CATEDRATICO (ID_CATEDRATICO, IDENTIFICACION, NOMBRE, TELEFONO, ESPECIALIDAD, ID_INSTITUTO) 
VALUES (4, '2800111110101', 'Karen Reyes', '44445555', 'Mecánica Automotriz e Industrial', 3);

INSERT INTO CATEDRATICO (ID_CATEDRATICO, IDENTIFICACION, NOMBRE, TELEFONO, ESPECIALIDAD, ID_INSTITUTO) 
VALUES (5, '2900222220101', 'Luis Álvarez', '44446666', 'Ciencias de la Computación', 1);


-- ESTUDIANTE
SET DEFINE OFF

INSERT INTO ESTUDIANTE (CARNE, NOMBRE_COMPLETO, CARRERA_TECNICA, DIRECCION, TELEFONO, FECHA_NACIMIENTO, GENERO, ES_REPITENCIA, ID_MUNICIPIO, ID_INSTITUTO) 
VALUES ('2024001', 'Diego López', 'Perito en Computación', 'Zona 5 Guatemala', '33331111', to_date('2005-04-12', 'RRRR-MM-DD'), 'M', 0, 1, 1);

INSERT INTO ESTUDIANTE (CARNE, NOMBRE_COMPLETO, CARRERA_TECNICA, DIRECCION, TELEFONO, FECHA_NACIMIENTO, GENERO, ES_REPITENCIA, ID_MUNICIPIO, ID_INSTITUTO) 
VALUES ('2024002', 'María Aguilar', 'Perito en Electrónica', 'Colonia El Milagro Mixco', '33332222', to_date('2006-08-25', 'RRRR-MM-DD'), 'F', 0, 3, 2);

INSERT INTO ESTUDIANTE (CARNE, NOMBRE_COMPLETO, CARRERA_TECNICA, DIRECCION, TELEFONO, FECHA_NACIMIENTO, GENERO, ES_REPITENCIA, ID_MUNICIPIO, ID_INSTITUTO) 
VALUES ('2024003', 'Pedro Samayoa', 'Perito en Computación', 'Zona 4 Villa Nueva', '33333333', to_date('2005-11-03', 'RRRR-MM-DD'), 'M', 1, 2, 1);

INSERT INTO ESTUDIANTE (CARNE, NOMBRE_COMPLETO, CARRERA_TECNICA, DIRECCION, TELEFONO, FECHA_NACIMIENTO, GENERO, ES_REPITENCIA, ID_MUNICIPIO, ID_INSTITUTO) 
VALUES ('2024004', 'Sara Pinzón', 'Perito Contador', 'Zona 10 Guatemala', '33334444', to_date('2006-01-15', 'RRRR-MM-DD'), 'F', 0, 1, 1);

INSERT INTO ESTUDIANTE (CARNE, NOMBRE_COMPLETO, CARRERA_TECNICA, DIRECCION, TELEFONO, FECHA_NACIMIENTO, GENERO, ES_REPITENCIA, ID_MUNICIPIO, ID_INSTITUTO) 
VALUES ('2024005', 'Fernando Cruz', 'Perito en Mecánica', 'Zona 1 Palín', '33335555', to_date('2005-09-10', 'RRRR-MM-DD'), 'M', 0, 7, 3);

INSERT INTO ESTUDIANTE (CARNE, NOMBRE_COMPLETO, CARRERA_TECNICA, DIRECCION, TELEFONO, FECHA_NACIMIENTO, GENERO, ES_REPITENCIA, ID_MUNICIPIO, ID_INSTITUTO) 
VALUES ('2024006', 'Gabriela Soto', 'Perito en Computación', 'Zona 15 Guatemala', '33336666', to_date('2006-03-22', 'RRRR-MM-DD'), 'F', 0, 1, 1);

INSERT INTO ESTUDIANTE (CARNE, NOMBRE_COMPLETO, CARRERA_TECNICA, DIRECCION, TELEFONO, FECHA_NACIMIENTO, GENERO, ES_REPITENCIA, ID_MUNICIPIO, ID_INSTITUTO) 
VALUES ('2024007', 'Andrés Barrios', 'Perito en Computación', 'Residenciales San José', '33337777', to_date('2005-12-05', 'RRRR-MM-DD'), 'M', 0, 2, 1);


-- COLOCACION
SET DEFINE OFF

INSERT INTO COLOCACION (ID_COLOCACION, FECHA_INICIO, FECHA_FINALIZACION, ID_ESTUDIANTE, ID_PLAZA, ID_CATEDRATICO, ID_ESTADO) 
VALUES (1, to_date('2026-07-01', 'RRRR-MM-DD'), to_date('2026-08-30', 'RRRR-MM-DD'), '2024001', 1, 1, 1);

INSERT INTO COLOCACION (ID_COLOCACION, FECHA_INICIO, FECHA_FINALIZACION, ID_ESTUDIANTE, ID_PLAZA, ID_CATEDRATICO, ID_ESTADO) 
VALUES (2, to_date('2026-07-15', 'RRRR-MM-DD'), to_date('2026-09-15', 'RRRR-MM-DD'), '2024002', 3, 2, 1);

INSERT INTO COLOCACION (ID_COLOCACION, FECHA_INICIO, FECHA_FINALIZACION, ID_ESTUDIANTE, ID_PLAZA, ID_CATEDRATICO, ID_ESTADO) 
VALUES (3, to_date('2025-01-10', 'RRRR-MM-DD'), to_date('2025-03-10', 'RRRR-MM-DD'), '2024003', 2, 1, 2);

INSERT INTO COLOCACION (ID_COLOCACION, FECHA_INICIO, FECHA_FINALIZACION, ID_ESTUDIANTE, ID_PLAZA, ID_CATEDRATICO, ID_ESTADO) 
VALUES (4, to_date('2026-08-01', 'RRRR-MM-DD'), to_date('', 'RRRR-MM-DD'), '2024004', 4, 3, 1);

INSERT INTO COLOCACION (ID_COLOCACION, FECHA_INICIO, FECHA_FINALIZACION, ID_ESTUDIANTE, ID_PLAZA, ID_CATEDRATICO, ID_ESTADO) 
VALUES (5, to_date('2026-08-01', 'RRRR-MM-DD'), to_date('', 'RRRR-MM-DD'), '2024005', 5, 4, 1);

INSERT INTO COLOCACION (ID_COLOCACION, FECHA_INICIO, FECHA_FINALIZACION, ID_ESTUDIANTE, ID_PLAZA, ID_CATEDRATICO, ID_ESTADO) 
VALUES (6, to_date('2026-07-01', 'RRRR-MM-DD'), to_date('2026-08-10', 'RRRR-MM-DD'), '2024006', 6, 5, 2);

INSERT INTO COLOCACION (ID_COLOCACION, FECHA_INICIO, FECHA_FINALIZACION, ID_ESTUDIANTE, ID_PLAZA, ID_CATEDRATICO, ID_ESTADO) 
VALUES (7, to_date('2026-08-15', 'RRRR-MM-DD'), to_date('', 'RRRR-MM-DD'), '2024007', 7, 5, 1);


--BITACORA
SET DEFINE OFF

INSERT INTO BITACORA (ID_BITACORA, CORRELATIVO_MENSUAL, FECHA, HORAS_TRABAJADAS, ACTIVIDADES_REALIZADAS, OBSERVACIONES, ID_COLOCACION, ID_CONTACTO_VALIDADOR) 
VALUES (1, 1, to_date('2026-07-01', 'RRRR-MM-DD'), 8, 'Configuración de entorno de desarrollo para el proyecto web', 'Ninguna', 1, 1);

INSERT INTO BITACORA (ID_BITACORA, CORRELATIVO_MENSUAL, FECHA, HORAS_TRABAJADAS, ACTIVIDADES_REALIZADAS, OBSERVACIONES, ID_COLOCACION, ID_CONTACTO_VALIDADOR) 
VALUES (2, 2, to_date('2026-07-02', 'RRRR-MM-DD'), 8, 'Desarrollo de módulo de autenticación de usuarios', 'Se requirió apoyo en DB', 1, 1);

INSERT INTO BITACORA (ID_BITACORA, CORRELATIVO_MENSUAL, FECHA, HORAS_TRABAJADAS, ACTIVIDADES_REALIZADAS, OBSERVACIONES, ID_COLOCACION, ID_CONTACTO_VALIDADOR) 
VALUES (3, 1, to_date('2026-07-15', 'RRRR-MM-DD'), 6, 'Revisión y mantenimiento de tableros eléctricos zona B', '', 2, 2);

INSERT INTO BITACORA (ID_BITACORA, CORRELATIVO_MENSUAL, FECHA, HORAS_TRABAJADAS, ACTIVIDADES_REALIZADAS, OBSERVACIONES, ID_COLOCACION, ID_CONTACTO_VALIDADOR) 
VALUES (4, 2, to_date('2026-07-16', 'RRRR-MM-DD'), 8, 'Cambio de fusibles de alta tensión', '', 2, 2);

INSERT INTO BITACORA (ID_BITACORA, CORRELATIVO_MENSUAL, FECHA, HORAS_TRABAJADAS, ACTIVIDADES_REALIZADAS, OBSERVACIONES, ID_COLOCACION, ID_CONTACTO_VALIDADOR) 
VALUES (5, 1, to_date('2026-08-01', 'RRRR-MM-DD'), 8, 'Revisión de tractores y calibración de motores', 'Todo en orden', 5, 5);

INSERT INTO BITACORA (ID_BITACORA, CORRELATIVO_MENSUAL, FECHA, HORAS_TRABAJADAS, ACTIVIDADES_REALIZADAS, OBSERVACIONES, ID_COLOCACION, ID_CONTACTO_VALIDADOR) 
VALUES (6, 2, to_date('2026-08-02', 'RRRR-MM-DD'), 8, 'Cambio de aceite y filtros en maquinaria pesada', 'Faltó repuesto del filtro de aire', 5, 5);

INSERT INTO BITACORA (ID_BITACORA, CORRELATIVO_MENSUAL, FECHA, HORAS_TRABAJADAS, ACTIVIDADES_REALIZADAS, OBSERVACIONES, ID_COLOCACION, ID_CONTACTO_VALIDADOR) 
VALUES (7, 1, to_date('2026-07-30', 'RRRR-MM-DD'), 8, 'Limpieza de base de datos de clientes', 'Uso de scripts SQL', 6, 6);

INSERT INTO BITACORA (ID_BITACORA, CORRELATIVO_MENSUAL, FECHA, HORAS_TRABAJADAS, ACTIVIDADES_REALIZADAS, OBSERVACIONES, ID_COLOCACION, ID_CONTACTO_VALIDADOR) 
VALUES (8, 2, to_date('2026-07-31', 'RRRR-MM-DD'), 8, 'Creación de dashboard en PowerBI', 'Terminado con éxito', 6, 6);

INSERT INTO BITACORA (ID_BITACORA, CORRELATIVO_MENSUAL, FECHA, HORAS_TRABAJADAS, ACTIVIDADES_REALIZADAS, OBSERVACIONES, ID_COLOCACION, ID_CONTACTO_VALIDADOR) 
VALUES (9, 1, to_date('2026-08-15', 'RRRR-MM-DD'), 6, 'Inducción a la arquitectura del sistema y repositorios', '', 7, 7);


-- EVALUACION
SET DEFINE OFF

INSERT INTO EVALUACION (ID_EVALUACION, FECHA_EVALUACION, ID_COLOCACION, ID_CATEDRATICO, ID_TIPO_EVALUACION) 
VALUES (1, to_date('2026-07-16', 'RRRR-MM-DD'), 1, 1, 1);

INSERT INTO EVALUACION (ID_EVALUACION, FECHA_EVALUACION, ID_COLOCACION, ID_CATEDRATICO, ID_TIPO_EVALUACION) 
VALUES (2, to_date('2025-03-10', 'RRRR-MM-DD'), 3, 1, 2);

INSERT INTO EVALUACION (ID_EVALUACION, FECHA_EVALUACION, ID_COLOCACION, ID_CATEDRATICO, ID_TIPO_EVALUACION) 
VALUES (3, to_date('2026-07-30', 'RRRR-MM-DD'), 2, 2, 1);

INSERT INTO EVALUACION (ID_EVALUACION, FECHA_EVALUACION, ID_COLOCACION, ID_CATEDRATICO, ID_TIPO_EVALUACION) 
VALUES (4, to_date('2026-08-10', 'RRRR-MM-DD'), 6, 5, 2);


-- DETALLE_EVALUACION
SET DEFINE OFF

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (1, 1, 5);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (1, 2, 4);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (1, 3, 5);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (1, 4, 3);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (1, 5, 4);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (2, 1, 4);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (2, 2, 5);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (2, 4, 4);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (3, 1, 5);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (3, 2, 5);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (3, 3, 4);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (3, 5, 5);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (4, 1, 5);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (4, 2, 4);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (4, 3, 5);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (4, 4, 5);

INSERT INTO DETALLE_EVALUACION (ID_EVALUACION, ID_CRITERIO, PUNTUACION) 
VALUES (4, 5, 4);

