-- Consulta 1: Directorio de Estudiantes Activos

SELECT
    e.CARNE,
    e.NOMBRE_COMPLETO,
    emp.NOMBRE AS EMPRESA,
    p.ESPECIALIDAD_TECNICA
FROM ESTUDIANTE e
JOIN COLOCACION c   ON e.CARNE = c.ID_ESTUDIANTE
JOIN PLAZA p        ON c.ID_PLAZA = p.ID_PLAZA
JOIN EMPRESA emp    ON p.ID_EMPRESA = emp.ID_EMPRESA
JOIN ESTADO_COLOCACION ec ON c.ID_ESTADO = ec.ID_ESTADO
WHERE ec.NOMBRE = 'Activa';