-- Consulta 5: Auditoría de Bitácoras

SELECT
    c.ID_COLOCACION,
    est.NOMBRE_COMPLETO AS ESTUDIANTE,
    cat.NOMBRE AS CATEDRATICO_SUPERVISOR
FROM COLOCACION c
JOIN ESTADO_COLOCACION ec ON c.ID_ESTADO = ec.ID_ESTADO
JOIN ESTUDIANTE est       ON c.ID_ESTUDIANTE = est.CARNE
JOIN CATEDRATICO cat      ON c.ID_CATEDRATICO = cat.ID_CATEDRATICO
LEFT JOIN BITACORA b ON c.ID_COLOCACION = b.ID_COLOCACION
                     AND b.FECHA >= ADD_MONTHS(SYSDATE, -1)
WHERE ec.NOMBRE = 'Activa'
  AND b.ID_BITACORA IS NULL;