-- Consulta 3: Carga de Validación por Contacto Empresarial

SELECT
    ce.NOMBRE AS CONTACTO,
    emp.NOMBRE AS EMPRESA,
    SUM(b.HORAS_TRABAJADAS) AS TOTAL_HORAS_VALIDADAS
FROM CONTACTO_EMPRESARIAL ce
JOIN EMPRESA emp   ON ce.ID_EMPRESA = emp.ID_EMPRESA
JOIN BITACORA b    ON ce.ID_CONTACTO = b.ID_CONTACTO_VALIDADOR
WHERE b.FECHA BETWEEN TO_DATE('2026-07-01', 'RRRR-MM-DD') AND TO_DATE('2026-08-31', 'RRRR-MM-DD')
GROUP BY ce.NOMBRE, emp.NOMBRE
ORDER BY TOTAL_HORAS_VALIDADAS DESC;