-- Consulta 4: Estudiantes en Repitencia

SELECT DISTINCT
    e.NOMBRE_COMPLETO,
    i.NOMBRE AS INSTITUTO,
    ce.NOMBRE AS CONTACTO_VALIDADOR,
    ec.NOMBRE AS ESTADO_COLOCACION
FROM ESTUDIANTE e
JOIN INSTITUTO i          ON e.ID_INSTITUTO = i.ID_INSTITUTO
JOIN COLOCACION c         ON e.CARNE = c.ID_ESTUDIANTE
JOIN ESTADO_COLOCACION ec ON c.ID_ESTADO = ec.ID_ESTADO
JOIN PLAZA p              ON c.ID_PLAZA = p.ID_PLAZA
JOIN CONTACTO_EMPRESARIAL ce ON p.ID_CONTACTO = ce.ID_CONTACTO
WHERE e.ES_REPITENCIA = 1;